[package]
name = "omnius-core-migration"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }

[features]
stable-test = []
postgres = ["tokio", "tokio-postgres"]
sqlite = ["dep:sqlx"]

[dependencies]
omnius-core-base = { workspace = true }

chrono = { workspace = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true }
sqlx = { version = "0.9.0", default-features = false, features = [
  "sqlite",
  "chrono",
  "macros",
  "runtime-tokio",
], optional = true }
tokio-postgres = { version = "0.7.17", features = ["with-chrono-0_4"], optional = true }

[dev-dependencies]
omnius-core-testkit = { workspace = true }
serial_test = { workspace = true }
tempfile = { workspace = true }
testresult = { workspace = true }
tokio = { workspace = true }
