[package]
name = "omnius-core-omnikit"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
omnius-core-base = { workspace = true }
omnius-core-rocketpack = { workspace = true }

rand = { workspace = true }
rand_core = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
futures-util = { workspace = true }
nom = { workspace = true }
sha3 = { workspace = true }
chrono = { workspace = true }
hkdf = { workspace = true }
aes-gcm = { workspace = true }
parking_lot = { workspace = true }
x25519-dalek = { workspace = true }
ed25519-dalek = { workspace = true }

[dev-dependencies]
testresult = { workspace = true }
