name: update-rust-toolchain

on:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update rust toolchain file
        id: update_rust_toolchain
        run: |
          RUST_VERSION=$(curl https://api.github.com/repos/rust-lang/rust/releases | jq -r -c '.[0] | select(.draft == false and .prerelease == false) | .tag_name')
          echo $RUST_VERSION > rust-toolchain
          echo "rust_version=$RUST_VERSION" >> $GITHUB_OUTPUT

      - name: Update github-actions
        run: python .github/workflows/update-rust-toolchain.py

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_WORKFLOW_UPDATE }}
          base: ${{ github.head_ref }}
          title: "[Update] Rust toolchain version ${{ steps.update_rust_toolchain.outputs.rust_version }}"
          commit-message: "[Update] Rust toolchain version ${{ steps.update_rust_toolchain.outputs.rust_version }}"
          branch: features/update-rust-version
          delete-branch: true
